// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkdunqataebjqkuhjige.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprZHVucWF0YWVianFrdWhqaWdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU3MTk4NjUsImV4cCI6MjA1MTI5NTg2NX0.eHBZ9QAeu1j0WZDi_L-F2EYaN8CUzU2ViQYIEwYcmPQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);